# Generated by Django 3.0.4 on 2020-03-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='NONE', max_length=100),
            preserve_default=False,
        ),
    ]
