# Generated by Django 3.0.4 on 2020-03-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(upload_to='uploads/applications/'),
        ),
    ]
